homeassistant:
  # Name of the location where Home Assistant is running
  name: home
  # C for Celcius, F for Fahrenheit
  temperature_unit: C
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Madrid
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: 119
  unit_system: metric
  customize: !include customize.yaml

http:
  api_password: !secret ha_api_password
  approved_ips:
    - 127.0.0.1
#  ssl_certificate: !secret ha_ssl_certificate
#  ssl_key: !secret ha_ssl_key
  #server_port: 8123
  #development: 1

  # Enables the frontend
frontend:

# Allows you to issue voice commands from the frontend
conversation:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Discover some devices automatically
discovery:

# Checks for available updates
updater:

# Enables support for tracking state changes over time.
history:

recorder:
  purge_days: 10

mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

#logger:
#  default: critical
#  logs:
#    homeassistant.components.sensor.command_line: critical
#    homeassistant.components.switch.command_line: critical

notify:
  - name: telegram
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chat_id

  - name: HTML5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

#  - platform: pushbullet
#    name: pushbullet
#    api_key: !secret pushbullet_api_key

ifttt:
  key: !secret ifttt_api_key

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password

shell_command: !include shell_command.yaml
device_tracker: !include device_tracker.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
group: !include groups.yaml
automation: !include automation.yaml
script: !include scripts.yaml
#scene: !include scenes.yaml
