- alias: 'Energy - Notification - Power back normal'
  trigger:
    - platform: state
      entity_id: sensor.energy_ups_status
      to: 'Cargando'
    - platform: state
      entity_id: sensor.energy_ups_status
      to: 'Normal'
  condition:
    - condition: numeric_state
      entity_id: sensor.ha_runtime_in_minutes
      above: 2
  action:
    - service: notify.telegram
      data:
        message: 'ðŸ”Œ Suministro elÃ©ctrico reestablecido'
    - service: notify.slack
      data_template:
        message: ''
        data:
          blocks:
            - type: 'divider'
            - type: 'section'
              text:
                type: 'mrkdwn'
                text: ':flash: Suministro elÃ©ctrico restablecido'
            - type: 'divider'
