- alias: 'Swimming Pool - Pump - Off time'
  trigger: 
    platform: template
    value_template: '{{states.sensor.date_time.state == states.sensor.piscina_off_time.state}}'
  action:
    - service: switch.turn_off
      entity_id: switch.motor_piscina