- alias: 'Webhook - Slack - Received'
  trigger:
    - platform: webhook
      webhook_id: slack-webhook
  action:
     # Execute service with the format <service>#<entity_id>.
     # If the service or the entity id don't exist, the execution will silently fail
    - service_template: >-
        {% set action = trigger.data.payload.split(",")[3].replace("]","").replace("}","").split(":")[1].replace("\"","").split("#") %}
        {{ action[0] }}

      data_template:
        entity_id: >-
          {% set action = trigger.data.payload.split(",")[3].replace("]","").replace("}","").split(":")[1].replace("\"","").split("#") %}
          {{ action[1] }}